/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }
    
    private void abrirVentana(javax.swing.JInternalFrame ventana) {

    for (javax.swing.JInternalFrame frame : desktop.getAllFrames()) {
        if (frame.getClass().equals(ventana.getClass())) {
            frame.toFront();
            return;
        }
    }

    desktop.add(ventana);
    ventana.setVisible(true);

    ventana.setLocation(
            (desktop.getWidth() - ventana.getWidth()) / 2,
            (desktop.getHeight() - ventana.getHeight()) / 2
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuVehiculos = new javax.swing.JMenuItem();
        mnuPedidos = new javax.swing.JMenuItem();
        mnuEntregas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        jMenu1.setText("Sistema");

        mnuCerrarSesion.setText("Cerrar Sesion");
        mnuCerrarSesion.addActionListener(this::mnuCerrarSesionActionPerformed);
        jMenu1.add(mnuCerrarSesion);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(this::mnuSalirActionPerformed);
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestion");
        jMenu2.addActionListener(this::jMenu2ActionPerformed);

        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(this::mnuClientesActionPerformed);
        jMenu2.add(mnuClientes);

        mnuVehiculos.setText("Vehiculos");
        mnuVehiculos.addActionListener(this::mnuVehiculosActionPerformed);
        jMenu2.add(mnuVehiculos);

        mnuPedidos.setText("Pedidos");
        mnuPedidos.addActionListener(this::mnuPedidosActionPerformed);
        jMenu2.add(mnuPedidos);

        mnuEntregas.setText("Entregas");
        mnuEntregas.addActionListener(this::mnuEntregasActionPerformed);
        jMenu2.add(mnuEntregas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSesionActionPerformed
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Desea cerrar sesión?",
        "Cerrar sesión",
        javax.swing.JOptionPane.YES_NO_OPTION
);

if (opcion == javax.swing.JOptionPane.YES_OPTION) {
    Login login = new Login();
    login.setVisible(true);
    this.dispose();
}        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCerrarSesionActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Desea salir del sistema?",
        "Salir",
        javax.swing.JOptionPane.YES_NO_OPTION
);

if (opcion == javax.swing.JOptionPane.YES_OPTION) {
    System.exit(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPedidosActionPerformed
        abrirVentana(new Pedidos());        // TODO add your handling code here:
    }//GEN-LAST:event_mnuPedidosActionPerformed

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        abrirVentana(new Clientes());        // TODO add your handling code here:
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVehiculosActionPerformed
        abrirVentana(new Vehiculos());        // TODO add your handling code here:
    }//GEN-LAST:event_mnuVehiculosActionPerformed

    private void mnuEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEntregasActionPerformed
        abrirVentana(new Entregas());        // TODO add your handling code here:
    }//GEN-LAST:event_mnuEntregasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuEntregas;
    private javax.swing.JMenuItem mnuPedidos;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuVehiculos;
    // End of variables declaration//GEN-END:variables
}
